version: "3"

services:
    app:
        build: ./docker/php
        container_name: app
        working_dir: /home/www
        environment:
            DB_HOST: ${DB_HOST}
            DB_DATABASE: ${DB_NAME}
            DB_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./www:/home/www
            - ./docker/php/php.ini:/usr/local/etc/conf.d/local.ini

    nginx:
        build: ./docker/nginx
        container_name: nginx
        ports:
            - "7777:80"
            - "443:443"
        volumes:
            - ./www:/home/www
            - ./docker/logs/nginx:/var/log/nginx

    mysql:
        container_name: mysql
        image: mysql:8.4.0
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
        ports:
            - "3306:3306"

    elasticsearch:
        image: elasticsearch:7.16.1
        container_name: elasticsearch
        environment:
            discovery.type: single-node
            ES_JAVA_OPTS: "-Xms512m -Xmx512m"
        ports:
            - "9200:9200"
            - "9300:9300"

    kibana:
        image: kibana:7.16.1
        container_name: kibana
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch